### ISSUE TITLE
IPV6 constants prevent users to create valid blocks / subnets

### ISSUE THREAD

**Issue by rockandska** [TeemIp/teemip-core-ip-mgmt#13]
Hi,

The constants used [here](https://github.com/TeemIp/teemip-core-ip-mgmt/blob/52c9da34a376f1116e1d8dfe988e6c779d7a9d7e/teemip-ipv6-mgmt/datamodel.teemip-ipv6-mgmt.xml#L1279-L1294) do not let users create valid IPV6 blocks /subnets.

Why not let users create /54 subnets for example ?

We could manually edit the generated php config file but will be erase in case of an update.

Regards,

**Comment by Hipska** [comment]
IPv6 subnets are always /64 by international convention. All above are considered subnet blocks in TeemIP.

Quote from [Wikipedia](https://en.wikipedia.org/wiki/IPv6):
> The IPv6 subnet size is standardized by fixing the size of the host identifier portion of an address to 64 bits.

But anyway, if you want to modify these constants, you can do so by creating your own extension where they get overridden.

**Comment by rockandska** [comment]
> IPv6 subnets are always /64 by international convention. All above are considered subnet blocks in TeemIP.

It is a recommendation not a strict rule

> Quote from [Wikipedia](https://en.wikipedia.org/wiki/IPv6):

Quote from [RFC5375](https://datatracker.ietf.org/doc/html/rfc5375#section-3)

>    However, some network administrators have used prefixes longer than
   /64 for links connecting routers, usually just two routers on a
   point-to-point link.  On links where all the addresses are assigned
   by manual configuration, and all nodes on the link are routers (not
   end hosts) that are known by the network, administrators do not need
   any of the IPv6 features that rely on /64 subnet prefixes, this can
   work.  Using subnet prefixes longer than /64 is not recommended for
   general use, and using them for links containing end hosts would be
   an especially bad idea, as it is difficult to predict what IPv6
   features the hosts will use in the future.

>    Using /64 subnets is strongly recommended, also for links connecting
   only routers.  A deployment compliant with the current IPv6
   specifications cannot use other prefix lengths.  However, the V6OPS
   WG believes that despite the drawbacks (and a potentially expensive
   network redesign, if IPv6 features relying on /64 subnets are needed
   in the future), some networks administrators will use prefixes longer
   than /64.

The keyword here is "not recommended", not "strictly forbidden" and we are in a case described in RFC where network administrators are aware of the RFC and side effects of choosing a prefix < 64.

Regards,

**Comment by Hipska** [comment]
You are absolutely right, so for these not recommended use-cases it is possible to override the constants with your extension, so it even stays/works in case of updates.

**Comment by xtophe38** [comment]
IMHO, when the [RFC5375 ](https://datatracker.ietf.org/doc/html/rfc5375#section-3 ) quoted here above talks about networks with a prefix that is longer to /64, it actually refers to networks with fewer host bits, that is networks in the /65 - /128 range. 

I must admit that the naming of IPv6 constants within TeemIp is probably confusing:
- by IPV6_SUBNET_MAX_PREFIX, we should read the **biggest / maximum** size that an IPv6 subnet may have: /64 by default (/56 is then forbidden but /70 is not). 
- by IPV6_SUBNET_MIN_PREFIX, we should read the **smallest / minimum ** size (in number of IPs) that such subnet may have: /128 = 1 IP by default. 
So, by default, TeemIp allows you to define your IPv6 subnets with prefixes in the /64 - /128 range, which makes it fully aligned with the RFC5375...

As @Hipska is mentioning: you may change these constants in you extension. But should you follow that path, I'd recommend you to thorough fully test to make sure that everything still work as expected.
