### ISSUE TITLE
Making the creation of many Subnet Blocks easier.

### ISSUE THREAD

**Issue by elysch** [TeemIp/teemip-core-ip-mgmt#14]
Hello. First of all, Great work. Thank you.

Ok, I can understand we don't want to use subnets with prefix from /48 to /63.  (See [IPV6 constants prevent users to create valid blocks / subnets #13](https://github.com/TeemIp/teemip-core-ip-mgmt/issues/13)

I need to create many Subnet Bocks. I'm about to get assigned a /44 Subnet Block. Then I need to create 8 Subnet Blocks with prefix /48, then from one of those with prefix /48 create 16 new Subnet Blocks with prefix /52, then another 16 with prefix /56 then a lot of subnets with prefix /64. And so on.

It’s not particularly difficult, I know. But once you create one of those, you cannot change the first IP and last IP, cannot change the parent Subnet Block, cannot change the organization and is not possible to change the specific settings for the Subnet Block (“Global Settings” tab) so you need to delete and re-create those with errors. At the end, it's a lot of work. If the block is not used yet, why is not possible to change those values?

Why in the IPv6 Subnet Block there is no mention of the prefix number?

Thinking about it, I think got a way to facilitate things. It would be much easier if the user could specify a prefix and take the first IP from the parent (the first available) and calculate the last IP (being able to change them, of course). 

Maybe I'm not understanding the logic behind it. Could you explain please?

Could you also please explain why was necessary to create a Subnet Block apart from a Subnet? 

Again, thank you.

Ely.

**Comment by elysch** [comment]
Hello again.

I tried to use a csv import file to create some /52 subnet blocks. 

I couldn't. 

Since I don't yet have the global IP's assigned, I'm testing with invented values from `2001:abc:de5:2000::` to `2001:abc:de5:2fff:ffff:ffff:ffff:ffff`

If I create the Subnet Block using the UI, it works just fine. But if I put the same First IP and Last IP in the csv file I get the error message: 
`Issue: Internal error: CoreCannotSaveObjectException, Block size cannot be smaller than 48 for organization XXXXXXXXX!: issues = {0=>Block size cannot be smaller than 48 for organization XXXXXXXXX!}, class = IPv6Block, id =`

I'm using IPAM for iTop Version: 2.7.0

**Comment by Hipska** [comment]
Could you also add the csv file you used to try this?

**Comment by Hipska** [comment]
Hi @elysch can you test if this still occurs wit TeemIp 3.1.0?

**Comment by Hipska** [comment]
@elysch ?

**Comment by xtophe38** [comment]
With no answer from you, @elysch, I'm closing the issue.
For your reference, you may have a look at the [wiki ](https://wiki.teemip.net) where the usage of IP Objects is described in detail.
