### ISSUE TITLE
open subnet block

### ISSUE THREAD

**Issue by joyhu** [TeemIp/teemip-core-ip-mgmt#21]
open subnet block

Fatal error: Uncaught Error: Call to a member function GetKey() on null in /var/www/html/env-production/teemip-ip-mgmt/src/Hook/IPMgmtExtraMenus.php:44 Stack trace: #0 /var/www/html/application/utils.inc.php(1571): TeemIp\TeemIp\Extension\IPManagement\Hook\IPMgmtExtraMenus::EnumItems() #1 /var/www/html/application/displayblock.class.inc.php(2180): utils::GetPopupMenuItemsBlock() #2 /var/www/html/sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php(156): MenuBlock->GetRenderContent() #3 /var/www/html/sources/Application/UI/Base/Component/DataTable/DataTableUIBlockFactory.php(83): Combodo\iTop\Application\UI\Base\Component\DataTable\DataTableUIBlockFactory::RenderDataTable() #4 /var/www/html/application/displayblock.class.inc.php(1447): Combodo\iTop\Application\UI\Base\Component\DataTable\DataTableUIBlockFactory::MakeForResult() #5 /var/www/html/application/displayblock.class.inc.php(768): DisplayBlock->RenderList() #6 /var/www/html/application/displayblock.class.inc.php(558): DisplayBlock->GetRenderContent() #7 /var/www/html/application/displayblock.class.inc.php(528): DisplayBlock->GetDisplay() #8 /var/www/html/env-production/teemip-framework/src/Helper/IPUtils.php(405): DisplayBlock->Display() #9 /var/www/html/env-production/teemip-ip-mgmt/src/Model/_IPBlock.php(404): TeemIp\TeemIp\Extension\Framework\Helper\IPUtils::DisplayTabContent() #10 /var/www/html/env-production/teemip-ip-mgmt/src/Model/_IPv4Block.php(1651): TeemIp\TeemIp\Extension\IPManagement\Model\_IPBlock->DisplayBareRelations() #11 /var/www/html/application/cmdbabstract.class.inc.php(1124): TeemIp\TeemIp\Extension\IPManagement\Model\_IPv4Block->DisplayBareRelations() #12 /var/www/html/pages/UI.php(441): cmdbAbstractObject->DisplayDetails() #13 {main} thrown in /var/www/html/env-production/teemip-ip-mgmt/src/Hook/IPMgmtExtraMenus.php on line 44
iTop: An error occurred, check server error log for more information.

**Comment by xtophe38** [comment]
Could you, please, tell us what setup you're using and what actions you did to trigger that event ? You may as well report you issues on SourceForge, under the [ticket ](https://sourceforge.net/p/teemip/tickets/) section.

**Comment by xtophe38** [comment]
Without any further details, I'm closing the issue.
