### ISSUE TITLE
Networkdevices eol field

### ISSUE THREAD

**Issue by dsm-museum-it** [TeemIp/teemip-core-ip-mgmt#22]
Hi there,

will you add eol_dates for networkdevices in future versions?
It would be nice to see, which devices needs to be swapped out.

**Comment by Hipska** [comment]
Sounds a good idea to have something like `replacement_date`, should that be a year or an actual date? (just think about how all different customers would want/use this differently)

Also this is not a thing that should be implemented by TeemIp IMHO. It should actually be added as a field to `PhysicalDevice` in core iTop.

If really wanted, you can quickly add this field yourself by the means of a custom extension, see [this how to](https://www.itophub.io/wiki/page?id=3_1_0:customization:add-attribute-sample) for reference.

**Comment by xtophe38** [comment]
I like the idea as well. True that such field should be directly added to the PhysicalDevice class, in iTop. However, until this happens, I could add make it available from the teemip-network-mgmt-extended with a "define_if_not_exists" statement.

**Comment by dsm-museum-it** [comment]
> Sounds a good idea to have something like `replacement_date`, should that be a year or an actual date? (just think about how all different customers would want/use this differently)
> 
> Also this is not a thing that should be implemented by TeemIp IMHO. It should actually be added as a field to `PhysicalDevice` in core iTop.
> 
> If really wanted, you can quickly add this field yourself by the means of a custom extension, see [this how to](https://www.itophub.io/wiki/page?id=3_1_0:customization:add-attribute-sample) for reference.

I also thought about customizing the teemip extension but it would be a kind of generic extension you might want to add anyway.

**Comment by dsm-museum-it** [comment]
> I like the idea as well. True that such field should be directly added to the PhysicalDevice class, in iTop. However, until this happens, I could add make it available from the teemip-network-mgmt-extended with a "define_if_not_exists" statement.

that would be nice !

**Comment by dsm-museum-it** [comment]
It would be nice if ```replacement_date``` would be an actual date field
Companies tend to have exact eol_dates for firmwares etc.

**Comment by xtophe38** [comment]
As mentioned by @Hipska, request has been fulfilled in extension[ TeemIp Network Management Extended](https://github.com/TeemIp/teemip-network-mgmt-extended).
