### ISSUE TITLE
IPAM - Error when try to edit a subnet block 

### ISSUE THREAD

**Issue by C00kiekiller** [TeemIp/teemip-core-ip-mgmt#28]
Hi,

when I try to edit an existing subnet block, I get the following error message in my browser:

URL shown in browser:
https://ipam.intern.xxxxxx.network/itop/pages/UI.php?operation=details&class=IPv4Block&id=5&c[menu]=IPv4Block

Error shown in browser: `iTop: An error occurred, check server error log for more information.`

It doesn't matter which subnet I select, the error occurs on all of them.
I have tried various browsers without success. (Edge, Chrome, Firefox)

Here is the error log from the Apache2 web server.
` /var/log/apache2/error.log` ([Pastebin](https://pastebin.com/V3udy5yz))

If you need more log files or information, just let me know. :-)

Using the three-dot menu on the right, I can edit the existing subnet blocks with the submenu item "Modify IPv4 Subnet Block objects...".
![itop_subnet_error_step4](https://github.com/TeemIp/teemip-core-ip-mgmt/assets/16733284/29d77cf7-97b5-4792-b665-33729af761f1)

**Operating Environment:**

- OS: Ubuntu Server 22.04 
- Webserver: Apache/2.4.52 (Ubuntu)
- PHP-Version: 8.1.2-1ubuntu2.14
- Database: 10.6.12-MariaDB-0ubuntu0.22.04.1

**iTop Informations**

- iTop version: iTop version 3.1.0-2-11973 built on 2023-08-02 14:25:30

**iTop Extensions**
- Mail to ticket automation 3.7.2
- Send updates by email 1.3.2
- IPAM for iTop 3.0.1

**Steps to reproduce:**

![itop_subnet_error_step1](https://github.com/TeemIp/teemip-core-ip-mgmt/assets/16733284/7c8dc907-9b59-467b-b5b9-eee3a0a6e788)
![itop_subnet_error_step2](https://github.com/TeemIp/teemip-core-ip-mgmt/assets/16733284/538c155f-430c-4382-a384-c3e71fbc5a5a)
![itop_subnet_error_step3](https://github.com/TeemIp/teemip-core-ip-mgmt/assets/16733284/462e2b6c-fb5e-4848-85c4-a0f909511731)

**Comment by xtophe38** [comment]
Hi,

That could be an issue related to PHP version. What I'd do in the first place is to upgrade "IPAM for iTop" to 3.1.3-2311 from [SourceForge](https://sourceforge.net/projects/teemip/files/latest/download)... and see how it goes. Thanks.

**Comment by C00kiekiller** [comment]
Hi,

after upgrading to version 3.1.3, the error no longer occurs. Thank you very much :-)

Kind regards
