### ISSUE TITLE
"Find and allocate IP space" results in PHP Fatal Error

### ISSUE THREAD

**Issue by izzy** [TeemIp/teemip-core-ip-mgmt#30]
In the current iTop 3.1.0 trying to use FindSpace results in a fatal error because the last argument of `cmdbAbstractObject::GetFormElementForField` is set to an empty string but must be an empty array or left out so the default of GetFormElementForField(which is also an empty array) can be used.

See: https://github.com/TeemIp/teemip-core-ip-mgmt/blob/3d1cd51b42bb7dbc5c407cd201782d6169044b2b/teemip-ip-mgmt/src/Controller/FindSpace.php#L400C68-L400C69

**Comment by xtophe38** [comment]
Thanks for the "headsup" ! This issue has already been corrected in the master branch on the 3rd of November. It will, of course, be included in the next revision that should be released before the end of the year.

**Comment by xtophe38** [comment]
Bug fix is now present in both IPAM for iTop 3.1.4 dated 2023/12/14 and TeemIp standalone 3.1.4 dated 2023/12/20.
