### ISSUE TITLE
IPAM on iTop and NAT link not displayed

### ISSUE THREAD

**Issue by mmusolesi** [TeemIp/teemip-core-ip-mgmt#9]
on TeemIP adding a NAT to one ip address object link both ip so if you go into anyone you can see the other one
On iTop if you add a NAT one IP going into the linked IP you are not aware of the NAT

try to explain into another way

suppose you have 2 IP: INTERNAL (1.1.1.1) and EXTERNAL (88.88.88.88)

you add NAT on INTERNAL linked to EXTERNAL and save

now go into EXTERNAL (88.88.88.88) -> tab NAT is empty

there is no way to know what is using EXTERNAL (88.88.88.88) for NAT

In teemIP stand alone link is bidirectional so you are able to avoid error

I do not know if is a bug or buy design, but i think you must have a way to get all IP NAT linking IPs in a bidirectional view

what do you think?

**Comment by xtophe38** [comment]
This behaviour is controlled by a TeemIp configuration parameter: "Symetrical IP NAT" in the "Default settings for IPs" section. Are you sure that the parameter is correctly set on your iTop + TeemIp instance ?

**Comment by mmusolesi** [comment]
Thanks a lot, I already found it!
it was a my fault, all works fine

Best Regards
